version: '3.7'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017
  assessment:
    build:
      context: .
      target: installer
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run test
    environment:
      - DB_URI=mongodb://root:rootpassword@mongodb:27017
      - DAYS_TO_REPEAT=13
    depends_on:
      - mongodb
